#Used by the Mongo implementation, currently the only one supported.
host: kahana.mongohq.com
port: 10011
database: minecraft
username: noyhillel #OPTIONAL, comment out to disable this
password: ilovetoeatcookies #OPTIONAL, comment out to disable this