formats:
    prefix: "&c[&bNetSentials&c] "
    tp-to-spawn: "&cYou have been teleported to spawn!"
    set-spawn: "&eYou have set the spawn!"
    home-set: "&aYou have set your home!"
    no-home: "&cYou haven't set a home!"
    tp-home: "&eYou have teleported home!"
    home-del: "&cYou have deleted your home!"
    send-message: "&3[&cYou &b> &c<target>&3] &e<message>"
    rec-message: "&3[&c<target> &b> &cYou&3] &e<message>"
    not-found: "&cPlayer not found."
    give-item-1: "&eYou have received 1 &3<item>&e!"
    give-item-2: "&eYou have received &3<amount> <item>&e(&3s&e)&e!"
    give-item-3: "&eYou have received &3<amount> <item>&e(&3s&e)&e at &3<durability> &edurability!"
    set-the-spawn: "&cYou need to set the spawn first!"

spawn:
  world:
  x:
  y:
  z:
  yaw:
  pitch:

module-listener:
  join: TRUE
  chat: TRUE
  leave: TRUE