name: NetSentials
version: 1.0
main: com.noyhillel.netsentials.NetSentials

commands:
    spawn:
        aliases: [s]
    home:
        aliases: [h]
    msg:
        aliases: [tell, message, whisper]
    reply:
        aliases: [r]
    i:
        aliases: [giveme, give]
    fly:
        aliases: [f]
    feed:
        aliases: [eat]
    heal:
        aliases: [health]