#Survival Games Created By NoyHillel1
#Feel free to customise as many of the messages/settings as you want!
#Hope you enjoy this plugin! Any questions, contact Noy at: noyhillel@gmail.com.
voting-length: 20 #Number of seconds until the game attempts to start
maximum-playes: 24 #Never set this higher than the number of cornicopia points in any map, because the game will not start if there are too many players for the map to handler
minimum-players: 2 #Default, adjust as needed! :3
deathmatch-size: 2
storage: storage
formats:
  prefix: "&e&l[&6&lSG&e&l] "
  join-msg: "&3<player> &b&l>> &ehas joined &6&lSG&e."
  voted-for-map: "&8You have voted for &6<map>&7!"
  voting-scoreboard-title: "&eType &c/vote [name]"
  time-remaining-lobby: "&7There are &e<time>&7 seconds until the game starts!"
  player-hit-by-snowball: "&c<player> &6has hit you with a snowball!"
  player-hit-by-egg: "&a<player> &6has hit you with an &eegg&6!"
  shutdown: "&cThe server will be shutting down in <seconds> seconds!"
  kick-game-over: "&3The game has ended! The winner was <victor>"
  disguised-player: "&6You have been disguised as; &5&l<nickname>&6!"
  boost-cooldown: "&cYou can only use that every &7&l[&e<time>&7&l] &cminutes!"
  boost-cooldown-time: 20
  boost: "&6You have been given a Help Boost! Things may not be going your way, but &cdon't &6give up!"
  cant-use-boost: "&cYou can't use that right now!"
  loss-points: "&cOuch! You lost &4<points> &cpoints for dying!"
  sendpoints: "&e<player> &ahas set your points to &c<points>!"
  setpoints: "&aYou have set &e<player>'s &apoints to &c<points>!"
  setcredits: "&e<player> &ahas set your points to &c<credits>!"
  sendcredits: "&aYou have set &e<player>'s &acredits to &c<credits>!"
  nick-off: "&cYou have undisguised"
  mutated: "&c<player> has now muted and seeks revenge on <killer>."
  no-mutation-passes: "&cYou do not have any mutation passes to mutate with!"
  tribute-fallen: "&5<fallen> &6was killed by &5<killer>"
  game-start: "&6A new game of SurvivalGames has begun! Good luck!"
  winner: "&6&l<victor> &chas won the &6&lSurvivalGames!"
  kicked-for-vip: "&cYou have been kicked to make room for a donator/VIP"
  setlobby: "&6You have set the lobby to the location you're standing in!"
  unsetlobby: "&6You have unset the lobby!"
  deathmatch-starting: "&cThe deathmatch countdown is now starting!"
  game-countdown: "&7There are &e<seconds>&7 seconds until the game starts!"
  deathmatch-countdown: "&7There are &e<seconds>&7 seconds until deathmatch starts!"
  time-to-deathmatch-countdown: "&cDeatchmatch starts in &7<seconds>&c!"
  force-dmatch: "&cYou have forced the Death Match to start!"
  deathmatch-countdown-start: "&aDeathmatch will start in 25 minutes!"
  deathmatch-start: "&6Deathmatch is starting! &4Good luck!"
  end-deathmatch-countdown: "&eDeathmatch will end in &l&e<seconds>"
  deathmatch-start-unmutate: "&4DeathMatch is starting, you have been unmutated!"
  points-got: "&eYou have received &4<points> points &efor that kill!"
  quit-msg: "&3<player> &c&l<< &ehas left &6&lSG&e."
  heal-msg: "&6You have been healed!"
  ender-winner: "&cThe winner is &e<victor>&c! &cCongrats!"
  healed-player: "&6You haved healed &4<target>"
  chest-refill: "&cThe Chests have refilled!"
  back-to-spawn: "&cYou're getting too far from spawn!"
  start-game: "&cYou have forcestarted the game!"
  chest-refill-time: 720 #IN SECONDS AFTER GAME STARTS.
  refill-chests: "&6Refilled the chests!"
  scoreboard:
    players: "&eTributes Left"
    spectators: "&cSpectators:"
    mutations: "&aMutations:"
    title: "&e&l[&6SG&e&l]"
  spectator-compass-title: "&aSpectator Compass"
  spectator-gui-name: "&5Who to?"
  teleport-spectator: "&6Teleported you to &b<target>!"
  mutation-interface-title: "&3Mutate"
  stats:
    header: "&3&l-----------&5[&9&lStats&5]&3&l------------"
    stat-display: "&9<name>&5 -- &9<stat>"
  vip-kick: "&cThere is no room on the server for you!"
database: #MUST CONFIGURE FOR PLUGIN TO WORK PROPERLY
  host: "localhost"
  port: '3306'
  username: "root"
  password: "google"
  database: "minecraft"
countdowns:
  pregame: 20
  pre-teleport-deathmatch: 20
  post-teleport-deathmatch: 20
  server-shutdown: 10
sounds:
  timer-sound: "UI_BUTTON_CLICK"
  timer-sound-higher: "ENTITY_EXPERIENCE_ORB_PICKUP"
mutation:
  disguise: "ZOMBIE"
  potion-effect-level: 3
pregame-book:
  title: "&cSurvivalGames"
  author: "NWSG" #Author, should change
  pages:
    - Welcome to &cThe Server!
    - <Insert Message Here>
    - You can edit the colors &ein the config! #Fill in
arena:
  name: "&cThis map is called: &6<name>"
  author: "&cThis map was made by: &6<author>"
  social-link: "&cWebsite/Social Link: &6<social>"
chat:
  spectator-chat: "&7[&cSpectator&7] &7<player>&a:&f "
  player-chat: "&6[&c<points>&6] &7<player>&a:&f "
  lobby-chat: "&7[&6LOBBY&7] &7<player>&a:&f "
enderbar:
  lobby-time: "&cWelcome, &6<player>&c"
  game-countdown-time: "&6Game starts in &c<time>"
  deathmatch-countdown-time: "&6Deathmatch starts in &c<time>"