name: NetSurvivalGames
version: 1.2
main: com.noyhillel.survivalgames.SurvivalGames
depends: [LibsDisguises, ProtocolLib] #not anymore

commands:
  vote:
    aliases: [v]
  map:
    aliases: [m, maps, arena, arenas]
  setup:
    aliases: [se]
  nick:
    aliases: [disguisePlayer, disguise, d]
  stats:
    alaises: [stat]
  linkchests:
    aliases: [lc]
  spawn:
    aliases: [s]
  setspawn:
    aliases: [ss]
  hub:
    aliases: [lobby, back, leave]
  spectate:
    aliases: [spec, view]
#  setcredits:
#    aliases: [sgsc]
  setpoints:
    aliases: [sgsp]
  refillchests:
    aliases: [rc]