name: NetSurvivalGames
version: 1.0
main: com.noyhillel.survivalgames.SurvivalGames
depends: [LibsDisguises, ProtocolLib]

commands:
  vote:
    aliases: [v]
  map:
    aliases: [m, maps, arena, arenas]
  setup:
    aliases: [se]
  nick:
    aliases: [disguisePlayer, disguise, d]
  stats:
    alaises: [stat]
  linkchests:
    aliases: [lc]
  spawn:
    aliases: [s]
  setspawn:
    aliases: [ss]
  hub:
    aliases: [lobby, back, leave]
  spectate:
    aliases: [spec, view]
