formats:
  prefix: "&c[&6Battledome&c] "
  build-phase-time: 20
  start-game: "&aThe game has started! Good luck!"
  join-message: "&6&l<name> &6has joined the game!"
  quit-message: "&6&l<name> &6has left the game!"
  phase-start: "&6&l<phase> &chas started!"
  ender-bar-ingame: "<team> &6-- &c<phase> &6-- "
  ender-bar-time-ingame: "&c<time>"
  team-obsidian: "&6&l<team>: &5Obsidian"
  game-won: "&6Congrats, you won!"
  battledome-over: "&4Game over! &cStats:<game-stats>"
  obsidian-placed: "&5Obsidian placed!"
  no-place-obsidian: "&cYou cannot place this!"
  holding-team-obsidian: "&bYou are the chosen one..."
  cannot-break-now: "&cYou cannot break this!"
  team-eliminated: "&6<team-destroyed> &celiminated!"
  do-not-cross: "&cYou cannot cross past this point!"
  heal: "&cYou have been healed."
  teleport: "&6Teleported to: &3<player>"
  kick-not-op-no-singleton: "You cannot join at this time!"
  battledome-over: "&cYou cannot join the game right now."
  seconds-left: "&cThere are &6<seconds> &cleft before battle phase!"
  spectate-chat: "&cYou cannot chat as a spectator"
  game-ending: "&cGame ending, thanks for playing!"